### ISSUE TITLE
After update to 1.4.0, it doesn't start (valueError: Namespace Handy not available)

### ISSUE THREAD

**Issue by felipehw** [flathub/org.gnome.Lollypop#106]
After the update to 1.4.0 version, the app doesn't start:
```
$ flatpak run org.gnome.Lollypop 
Traceback (most recent call last):
  File "/app/bin/lollypop", line 45, in <module>
    from lollypop.application import Application
  File "/app/lib/python3.7/site-packages/lollypop/application.py", line 18, in <module>
    gi.require_version("Handy", "1")
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Handy not available
$
```
Info about the flatpak used:
 ```
$ flatpak info org.gnome.Lollypop 

Lollypop - Play and organize your music collection

          ID: org.gnome.Lollypop
         Ref: app/org.gnome.Lollypop/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.4.0
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 37,2 MB
     Runtime: org.gnome.Platform/x86_64/3.36
         Sdk: org.gnome.Sdk/x86_64/3.36

      Commit: 88f86c95cb04359535e9440a78c6c70a2b13bb286dbbdf67b3b092c627f11879
      Parent: f8aa4ad609fe7e1a3bc55c8d7a87e6e4becd84ce785f9f98a24bc6ced325407e
     Subject: Update Lollypop to 1.4.0 (54a6ed96)
        Date: 2020-09-26 06:34:13 +0000
$
```

**Comment by Eonfge** [comment]
Can you check for updates? There should be a new version available that addresses this issue:

```
$ flatpak info org.gnome.Lollypop

Lollypop - Play and organise your music collection

          ID: org.gnome.Lollypop
         Ref: app/org.gnome.Lollypop/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.4.0
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 38.3 MB
     Runtime: org.gnome.Platform/x86_64/3.36
         Sdk: org.gnome.Sdk/x86_64/3.36

      Commit: 40b4b35b3cc4f46b313d3e82c52dc03f86d8c2d24cbb2b3b2e764714d353b313
      Parent: 88f86c95cb04359535e9440a78c6c70a2b13bb286dbbdf67b3b092c627f11879
     Subject: Include libhandy which was missing (a9ec9ac4)
        Date: 2020-09-26 21:52:21 +0000

```

**Comment by felipehw** [comment]
Solved
